import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { FaShoppingCart, FaInstagram } from "react-icons/fa";
import Header from "./components/Header";
import Modal from "./components/Modal";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fruit Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col ${inter.className}`}>
        <Header />
        <div className="flex-1">{children}</div>
        <footer className="flex items-center flex-wrap justify-center border-t border-solid border-slate-300 p-4 md:p-8">
          <Link href={"https://www.instagram.com/smoljames"} target="_blank">
            <FaInstagram className="text-slate-700 hover:text-slate-500 cursor-pointer text-2xl sm:text-3xl md:text-4xl" />
          </Link>
        </footer>
        <Modal />
      </body>
    </html>
  );
}
